Vikaba/Models/CreateNews.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;

namespace Vikaba.Models
{
    public class CreateNews
    {
        [Required]
        [DisplayName("Дата публикации")]
        public DateTime PublishedAt { get; set; }

        [Required]
        [MinLength(10)]
        [DisplayName("Заголовок")]
        public string Headline { get; set; } = "";

        [Required]
        [MinLength(10)]
        [DisplayName("Подзаголовок")]
        public string SubHeadline { get; set; } = "";

        [Required]
        [MinLength(20)]
        [DisplayName("Новость")]
        public string Content { get; set; } = "";

        [Required]
        [MinLength(5)]
        [DisplayName("Теги")]
        public string Tags { get; set; } = "";

        [DisplayName("Изображение")] public IFormFile? Image { get; set; }
    }
}

Vikaba/Models/CreateThread.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;

namespace Vikaba.Models
{
    public class CreateThread
    {
        [DisplayName("Элекронная почта")]
        [EmailAddress]
        public string Email { get; set; } = "";

        [DisplayName("Имя пользователя")] public string UserName { get; set; } = "";

        [DisplayName("Заголовок")] public string Headline { get; set; } = "";

        [Required] [DisplayName("Пост")] public string Content { get; set; } = "";

        [Required]
        [DisplayName("Изображение")]
        public IFormFile Image { get; set; } = null!;
    }
}

Vikaba/Models/ErrorViewModel.cs
namespace Vikaba.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Vikaba/Controllers/BoardController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Vikaba.Data;

namespace Vikaba.Controllers
{
    public class BoardController : Controller
    {
        private readonly ApplicationDbContext _db;

        // GET
        public BoardController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var categories = _db.Categories
                .Include(category => category.Boards)
                .ToArray();

            return View(categories);
        }
    }
}

Vikaba/Controllers/NewsController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Vikaba.Data;
using Vikaba.Models;

namespace Vikaba.Controllers
{
    public class NewsController : Controller
    {
        private readonly IWebHostEnvironment _environment;
        private readonly ApplicationDbContext _db;

        public NewsController(IWebHostEnvironment environment, ApplicationDbContext db)
        {
            _environment = environment;
            _db = db;
        }

        [HttpGet("/news")]
        public ActionResult News()
        {
            var news = _db.News
                .OrderByDescending(n => n.PublishedAt)
                .ToList();

            return View(news);
        }

        [HttpGet("/news/tag/{tagId}")]
        public ActionResult TagsToNews(string tagId)
        {
            var news = _db.News
                .Where(n => n.Tags
                    .Any(tag => tag.Title == tagId))
                .OrderByDescending(n => n.PublishedAt)
                .ToList();

            return View("News", news);
        }

        [HttpGet("/news/new")]
        public ActionResult PostNews()
        {
            return View();
        }

        [HttpPost("/news/new")]
        public ActionResult SaveNews(CreateNews news)
        {
            if (!ModelState.IsValid)
            {
                return View("PostNews", news);
            }

            var entity = new News
            {
                Headline = news.Headline,
                SubHeadline = news.SubHeadline,
                Content = news.Content,
                PublishedAt = news.PublishedAt,
            };
            
            foreach (var tag in news.Tags.Split())
            {
                var dbTag = _db.Tags
                    .FirstOrDefault(t => t.Title == tag);

                if (dbTag == null)
                {
                    dbTag = new Tag
                    {
                        Title = tag
                    };
                }
                
                entity.Tags.Add(dbTag);
            }
            
            if (news.Image != null)
            {
                var imageRelativePath = Path.Join("uploads", news.Image.FileName);
                var uploadPath = Path.Join(_environment.WebRootPath, imageRelativePath);
                using var uploadedFile = System.IO.File.Create(uploadPath);
                news.Image.CopyTo(uploadedFile);
                entity.Image = imageRelativePath;
            }

            _db.News.Add(entity);
            _db.SaveChanges();

            return RedirectToAction("News");
        }
    }
}

Vikaba/Controllers/ThreadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Vikaba.Data;
using Vikaba.Models;

namespace Vikaba.Controllers
{
    public class ThreadController : Controller
    {
        private readonly IWebHostEnvironment _environment;
        private readonly ApplicationDbContext _db;

        public ThreadController(IWebHostEnvironment environment,
            ApplicationDbContext db)
        {
            _environment = environment;
            _db = db;
        }

        [HttpGet("/{board}/")]
        public ActionResult BoardThreads(string board)
        {
            ViewBag.Board = board;

            var threads = _db.Threads
                .Include(thread => thread.Board)
                .Where(thread => thread.Board.Link == board)
                .ToList();

            return View(threads);
        }


        // /cg/res/2066095.html
        // /{board}/res/{threadId}.html
        [HttpGet("{board}/res/{threadId:int}.html")]
        public ActionResult ThreadComments(string board, int threadId)
        {
            var thread = _db.Threads
                .Where(thread => thread.Board.Link == board)
                .Where(thread => threadId == thread.Id)
                .FirstOrDefault();

            if (thread != null)
            {
                return View(thread);
            }

            return Content("Тред не найден");
        }

        [HttpGet("{board}/thread/new")]
        public ActionResult PostThread(string board)
        {
            ViewBag.Board = board;
            return View("CreateThread");
        }

        [HttpPost("{board}/create")]
        public ActionResult CreateThread(string board, CreateThread thread)
        {
            ViewBag.Board = board;

            if (!ModelState.IsValid)
            {
                return View(thread);
            }

            var imageRelativePath = Path.Join("uploads", thread.Image.FileName);
            var uploadPath = Path.Join(_environment.WebRootPath, imageRelativePath);
            using var uploadedFile = System.IO.File.Create(uploadPath);
            thread.Image.CopyTo(uploadedFile);

            var entity = new BoardThread()
            {
                Headline = thread.Headline,
                Content = thread.Content,
                Board = _db.Boards.First(b => b.Link == board),
                Image = imageRelativePath
            };

            _db.Threads.Add(entity);
            _db.SaveChanges();

            return RedirectToAction("ThreadComments", new {board = board, threadId = entity.Id});
        }
    }
}

Vikaba/Views/Board/Index.cshtml
@using Vikaba.Data
@model Vikaba.Data.BoardCategory[]

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Список досок</h2>


@foreach (BoardCategory category in Model)
{
    <h3>@category.Title</h3>
    <ul>
        @foreach (var board in category.Boards)
        {
            <li>
                <a href="/@board.Link">@board.Title</a>
            </li>
        }
    </ul>
}

Vikaba/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Vikaba/Views/News/News.cshtml
@model List<Vikaba.Data.News>

@{
    ViewBag.Title = "Все новости";
    Layout = "_Layout";
}

<h2>Все новости на сегодня</h2>

<a asp-controller="News" asp-action="PostNews" class="btn btn-primary">
    <i class="fa fa-plus"></i> Создать новость
</a>

<div>

    @foreach (var newsItem in Model)
    {
        <div class="news-item">
            <h2 class="news-headline">@newsItem.Headline</h2>
            <h3 class="news-subheadline">@newsItem.SubHeadline</h3>
            @if (newsItem.Image != null)
            {
                <img src="@newsItem.Image" alt="@newsItem.Headline">
            }
            <div class="news-content">@newsItem.Content</div>
            <span class="news-publishedat">@newsItem.PublishedAt</span>


            @foreach (var tagItem in newsItem.Tags)
            {
                <a asp-controller="News"
                   asp-action="TagsToNews"
                   asp-route-tagId="@tagItem.Title">
                    @tagItem.Title
                </a>
            }

        </div>
    }

</div>

Vikaba/Views/News/PostNews.cshtml
@model CreateNews

@{
    ViewBag.Title = "Создать новость";
    Layout = "_Layout";
}

<h2>Создание новости</h2>

@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger" asp-validation-summary="All"></div>
}

<form enctype="multipart/form-data" asp-action="SaveNews" class="news-form">
    <div class="form-group">
        <label asp-for="Headline">Заголовок</label>
        <input class="form-control" asp-for="Headline">
        <span class="text-danger" asp-validation-for="Headline"></span>
    </div>

    <div class="form-group">
        <label asp-for="SubHeadline">Подзаголовок</label>
        <input class="form-control" asp-for="SubHeadline">
        <span class="text-danger" asp-validation-for="SubHeadline"></span>
    </div>

    <div class="form-group">
        <label asp-for="Content">Содержание</label>
        <textarea class="form-control" asp-for="Content" rows="8" cols="40"></textarea>
        <span class="text-danger" asp-validation-for="Content"></span>
    </div>

    <div class="form-group">
        <label asp-for="Tags">Теги</label>
        <input class="form-control" asp-for="Tags">
        <span class="text-danger" asp-validation-for="Tags"></span>
    </div>

    <div class="form-group">
        <label asp-for="PublishedAt">Дата публикации</label>
        <input class="form-control" type="date" asp-for="PublishedAt">
        <span class="text-danger" asp-validation-for="PublishedAt"></span>
    </div>

    <div class="form-group">
        <label asp-for="Image">Картинка</label>
        <input asp-for="Image" class="form-control-file">
        <span class="text-danger" asp-validation-for="Image"></span>
    </div>

    <div>
        <button class="btn btn-primary" type="submit">Отправить</button>
        <button class="btn btn-default" type="reset">Сбросить</button>
    </div>

</form>

Vikaba/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Vikaba</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.min.css"/>

</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Board" asp-action="Index">Vikaba</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Board" asp-action="Index">Главная</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="News" asp-action="News">Новости</a>
                    </li>
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/lib/fontawesome/js/all.min.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Vikaba/Views/Thread/BoardThreads.cshtml
@using Vikaba.Data
@model List<BoardThread>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<a asp-controller="Thread" asp-action="PostThread"
   asp-route-board="@ViewBag.Board" class="btn btn-primary">
    <i class="fa fa-plus"></i> Создать тред
</a>

@foreach (BoardThread thread in Model)
{
    <div class="thread">
        <a asp-controller="Thread"
           asp-action="ThreadComments"
           asp-route-threadId="@thread.Id"
           asp-route-board="@thread.Board.Link">
            Ответ
        </a>
        <span class="postdate">@thread.CreatedAt</span>
        <span class="id">@thread.Id</span>
        <span class="subject">@thread.Headline</span>
        <blockquote class="usertext">@thread.Content</blockquote>

        @foreach (var comment in thread.Comments)
        {
            <div class="comment">
                <span class="postdate">@comment.CreatedAt</span>
                <span class="id">@comment.Id</span>
                <span class="username">@comment.UserName</span>
                <blockquote class="usertext">@comment.UserText</blockquote>
            </div>
        }
    </div>
}

Vikaba/Views/Thread/CreateThread.cshtml
@model CreateThread

@{
    ViewBag.Title = "Создание треда";
    Layout = "_Layout";
}

<h2>Создание треда</h2>

<form enctype="multipart/form-data" asp-action="CreateThread" asp-route-board="@ViewBag.Board" class="thread-form">

    <div class="form-group">
        <label asp-for="Email">Электронная почта</label>
        <input class="form-control" asp-for="Email">
        <span class="text-danger" asp-validation-for="Email"></span>
    </div>

    <div class="form-group">
        <label asp-for="UserName"></label>
        <input class="form-control" asp-for="UserName">
        <span class="text-danger" asp-validation-for="UserName"></span>
    </div>

    <div class="form-group">
        <label asp-for="Headline">Заголовок</label>
        <input class="form-control" asp-for="Headline">
        <span class="text-danger" asp-validation-for="Headline"></span>
    </div>

    <div class="form-group">
        <label asp-for="Content"></label>
        <textarea class="form-control" rows="8" asp-for="Content"></textarea>
        <span class="text-danger" asp-validation-for="Content"></span>
    </div>

    <div class="form-group">
        <label asp-for="Image">Картинка</label>
        <input asp-for="Image" class="form-control-file">
        <span class="text-danger" asp-validation-for="Image"></span>
    </div>

    <div>
        <button class="btn btn-primary" type="submit">Отправить</button>
        <button class="btn btn-default" type="reset">Сбросить</button>
    </div>


</form>

Vikaba/Views/Thread/ThreadComments.cshtml
@model Vikaba.Data.BoardThread

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div class="thread-post">
    <span class="post-no">@Model.Id</span>
    <span class="headline">@Model.Headline</span>
    <blockquote class="content">@Model.Content</blockquote>
    <span class="post-date">@Model.CreatedAt</span>
    <img src="/@Model.Image" alt="@Model.Headline">
</div>

@foreach (var comment in Model.Comments)
{
    <div class="comment">
        <span class="postdate">@comment.CreatedAt</span>
        <span class="id">@comment.Id</span>
        <span class="username">@comment.UserName</span>
        <blockquote class="usertext">@comment.UserText</blockquote>
    </div>
}